apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
  name: cluster-reader
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["statefulsets", "deployments", "replicasets"]
  verbs: ["get", "watch", "list"]


