apiVersion: v1
kind: Service
metadata:
  name: kubview
spec:
  type: LoadBalancer
  selector:
    app: kubview
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 4000
      targetPort: 4000

